import StyleDictionary from "style-dictionary-utils";
import { SerendieParser } from "./parser";
import "./formatter";
import "./transformer/cssShadow";
import "./transformer/cssTypography";

StyleDictionary.registerParser(SerendieParser);

const myStyleDictionary = StyleDictionary.extend({
  source: ["tokens/**/*.json"],
  fileHeader: {
    myFileHeader: () => {
      return ["DO NOT EDIT DIRECTLY", "Generated by Style Dictionary"];
    },
  },
  platforms: {
    css: {
      transformGroup: "css",
      transforms: [
        "attribute/cti",
        "name/cti/kebab",
        "color/css",
        "cssShadow",
        "cssTypography",
      ],
      buildPath: "dist/",
      options: {
        fileHeader: `myFileHeader`,
      },
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
        },
      ],
    },
    serendie: {
      options: {
        fileHeader: `myFileHeader`,
      },
      transforms: [
        "attribute/cti",
        "name/cti/camel",
        "time/seconds",
        "content/icon",
        "color/css",
      ],
      files: [
        {
          destination: "dist/tokens.js",
          format: "serendie-module",
        },
        {
          destination: "dist/tokens.d.ts",
          format: "serendie-module-declarations",
        },
        {
          destination: "dist/panda-tokens.js",
          format: "panda-css-module",
        },
        {
          destination: "dist/panda-tokens.d.ts",
          format: "panda-css-module-declarations",
        },
        {
          destination: "dist/token-list.js",
          format: "serendie-token-list",
        },
        {
          destination: "dist/token-list.d.ts",
          format: "serendie-token-list-declarations",
        },
      ],
    },
  },
});

myStyleDictionary.buildAllPlatforms();
