name: Build Design Tokens by StyleDictonary

on:
  push:
    branches:
      # - main
      - "**"
    paths:
      - "design-tokens/tokens/**"
      - ".github/workflows/build-tokens-and-create-pr.yml"

jobs:
  build-tokens-and-create-pr:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set NPM version
        run: npm install -g npm@latest

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Cache Dependency
        uses: actions/cache@v4
        id: cache_dependency
        env:
          cache-name: cache-dependency
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Run StyleDictonary
        run: npm run build -w design-tokens

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Build design tokens by StyleDictonary
          branch: update-design-token-dist
          delete-branch: true
          title: "Build design tokens by StyleDictonary"
          body: |
            This PR updates the build artifacts.
          reviewers: ${{ github.actor }}
