name: Comment for ui checking

on:
  pull_request:
    types: 
      - opened
    branches:
      - main
    paths:
      - "ui/**"

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "- [ ] ドキュメントサイトのComponentプレビュー内容は適切ですか\n- [ ] ドキュメントサイトのComponentサンプルコードは適切ですか\n- [ ] ドキュメントサイトからStorybookへのリンクは適切ですか\n- [ ] Storybook上の表示は適切ですか\n- [ ] CodeConnectの表示は適切ですか"
            })
