name: Publish to pkg.pr.new
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"

permissions:
  contents: read
  pull-requests: write

jobs:
  publish-to-pkg-pr-new:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: npx -y pkg-pr-new publish
