name: Release package

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package"
        required: true
        type: choice
        options:
          - ui
          - design-tokens
          - style-dictionary-formatter
      increment:
        description: "Increment"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Git User
        shell: bash
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1 -- ${{ github.event.inputs.package}})"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1 -- ${{ github.event.inputs.package}})"
      - name: Setup .npmrc
        run: cp ./.npmrc.example ./.npmrc
      - run: npm ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Release
        run: npm run release --prefix ${{ github.event.inputs.package }} --ci --increment ${{ github.event.inputs.increment }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
