name: Sync Design Tokens to Figma

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "design-tokens/tokens/**"
      - ".github/workflows/sync-json-to-figma.yml"

jobs:
  sync-tokens-to-figma:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set NPM version
        run: npm install -g npm@latest

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Cache Dependency
        uses: actions/cache@v4
        id: cache_dependency
        env:
          cache-name: cache-dependency
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Sync json to Figma file
        run: |
          npm run ci:sync-json-to-figma -w design-tokens  &> output.txt # 
          less output.txt
        env:
          FILE_KEY: ${{ secrets.SYNC_FIGMA_FILE_KEY }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.SYNC_FIGMA_PERSONAL_ACCESS_TOKEN }}

      - id: get-comment-body
        run: |
          body="$(cat output.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 📡 Sync Design Tokens to Figma
            ```bash
            ${{ steps.get-comment-body.outputs.body }}
            ```
          reactions: rocket
