name: Sync design-tokens to Figma

on:
  push:
    # branches:
    #   - main
    paths:
      - "design-tokens/tokens/**"
      - ".github/workflows/sync-json-to-figma.yml"
  workflow_dispatch:
    inputs:
      file_key:
        description: "The file key of the Figma file to be updated"
        required: true

jobs:
  sync-tokens-to-figma:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set NPM version
        run: npm install -g npm@latest

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Sync json to Figma file
        run: npm run sync-json-to-figma -w design-tokens
        env:
          FILE_KEY: ${{ secrets.SYNC_FIGMA_FILE_KEY }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.SYNC_FIGMA_PERSONAL_ACCESS_TOKEN }}
