name: Sync design-tokens to Figma

on:
  pull_request:
    branches:
      - main
    # types:
    #   - closed
    paths:
      - "design-tokens/tokens/**"
      - ".github/workflows/sync-json-to-figma.yml"
  workflow_dispatch:
    inputs:
      file_key:
        description: "The file key of the Figma file to be updated"
        required: true

jobs:
  sync-tokens-to-figma:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set NPM version
        run: npm install -g npm@latest

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache Dependency
        uses: actions/cache@v3
        id: cache_dependency
        env:
          cache-name: cache-dependency
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Sync json to Figma file
        run: |
          npm run sync-json-to-figma -w design-tokens  &> diff.txt # 
          less diff.txt
        env:
          FILE_KEY: ${{ secrets.SYNC_FIGMA_FILE_KEY }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.SYNC_FIGMA_PERSONAL_ACCESS_TOKEN }}

      - id: get-comment-body
        run: |
          body="$(cat diff.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🍰  diff 🍰 
            ```bash
            ${{ steps.get-comment-body.outputs.body }}
            ```
          reactions: rocket
